import * as path from "node:path";
import { sha256 } from "./canonical";

/** Model-visible transforms whose bytes must be present in the protected content root. */
export const IMPLEMENTATION_SOURCE_GLOBS = [
	// Agent message assembly, replay, and compaction.
	"packages/agent/src/agent-loop.ts",
	"packages/agent/src/index.ts",
	"packages/agent/src/agent.ts",
	"packages/agent/src/append-only-context.ts",
	"packages/agent/src/compaction.ts",
	"packages/agent/src/compaction/**/*.ts",
	"packages/agent/src/pause.ts",
	"packages/agent/src/proxy.ts",
	"packages/agent/src/replay-policy.ts",
	"packages/agent/src/run-collector.ts",
	"packages/agent/src/telemetry.ts",
	"packages/agent/src/thinking.ts",
	"packages/agent/src/tokenizer.ts",
	"packages/agent/src/types.ts",
	// Tool schema emitters and prompt rendering primitives.
	"packages/hashline/src/**/*.{lark,md,ts}",
	"packages/omptype/src/**/*.ts",
	"packages/snapcompact/src/**/*.{md,ts}",
	"packages/utils/src/frontmatter.ts",
	"packages/utils/src/format.ts",
	"packages/utils/src/fetch-retry.ts",
	"packages/utils/src/fs-error.ts",
	"packages/utils/src/index.ts",
	"packages/utils/package.json",
	"packages/utils/src/dirs.ts",
	"packages/utils/src/binary.ts",
	"packages/utils/src/acp/connection.ts",
	"packages/utils/src/acp/protocol.ts",
	"packages/utils/src/acp/schema.ts",
	"packages/utils/src/acp/stream.ts",
	"packages/utils/src/acp/transport.ts",
	"packages/utils/src/json.ts",
	"packages/utils/src/mime.ts",
	"packages/utils/src/path-tree.ts",
	"packages/utils/src/readability/readability.ts",
	"packages/utils/src/readability/readerable.ts",
	"packages/utils/src/runtime-install.ts",
	"packages/utils/src/stream.ts",
	"packages/utils/src/tls-fetch.ts",
	"packages/utils/src/turndown/gfm.ts",
	"packages/utils/src/turndown/html.ts",
	"packages/utils/src/turndown/service.ts",
	"packages/utils/src/type-guards.ts",
	"packages/utils/src/tab-spacing.ts",
	"packages/utils/src/prompt.ts",
	"packages/utils/src/sanitize-text.ts",
	"packages/utils/src/template.ts",
	"packages/utils/src/version.ts",
	"packages/wire/src/index.ts",
	// Repository documentation served verbatim through the omp:// read-tool protocol.
	"docs/**/*.md",
	// Native tool-output transforms invoked by registered structured tools.
	"crates/pi-natives/src/ast.rs",
	"crates/pi-natives/src/block.rs",
	"crates/pi-natives/src/diff.rs",
	"crates/pi-natives/src/audio.rs",
	"crates/pi-natives/src/clipboard.rs",
	"crates/pi-natives/src/crash_handler.rs",
	"crates/pi-natives/src/devicecheck.rs",
	"crates/pi-natives/src/desktop/**/*.rs",
	"crates/pi-natives/src/file_lock/mod.rs",
	"crates/pi-natives/src/file_lock/linux.rs",
	"crates/pi-natives/src/file_lock/unix.rs",
	"crates/pi-natives/src/file_lock/windows.rs",
	"crates/pi-natives/src/glob.rs",
	"crates/pi-natives/src/glob_util.rs",
	"crates/pi-natives/src/grep.rs",
	"crates/pi-natives/src/html.rs",
	"crates/pi-natives/src/iofs.rs",
	"crates/pi-natives/src/iso.rs",
	"crates/pi-natives/src/lib.rs",
	"crates/pi-natives/src/live.rs",
	"crates/pi-natives/src/pdf.rs",
	"crates/pi-natives/src/ps.rs",
	"crates/pi-natives/src/pty.rs",
	"crates/pi-natives/src/power.rs",
	"crates/pi-natives/src/shell.rs",
	"crates/pi-natives/src/snapcompact.rs",
	"crates/pi-natives/src/summary.rs",
	"crates/pi-natives/src/task.rs",
	"crates/pi-natives/src/tokens.rs",
	"crates/pi-natives/src/vectors.rs",
	"crates/pi-natives/src/workspace.rs",
	"crates/pi-natives/src/utils.rs",
	"crates/pi-ast/src/block.rs",
	"crates/pi-ast/src/lib.rs",
	"crates/pi-ast/src/ops.rs",
	"crates/pi-ast/src/summary.rs",
	"crates/pi-walker/src/cache.rs",
	"crates/pi-walker/src/lib.rs",
	"crates/pi-iso/src/**/*.rs",
	"crates/pi-shell/build.rs",
	"crates/pi-shell/src/**/*.rs",
	"crates/pi-shell/src/minimizer/defs/*.toml",
	"crates/pi-voice/src/**/*.rs",
	"crates/pi-natives/src/fonts/5x8.bdf",
	"crates/pi-natives/src/fonts/6x12.bdf",
	"crates/pi-natives/src/fonts/8x13.bdf",
	"crates/pi-natives/src/fonts/Silver.ttf",
	"crates/pi-natives/src/fonts/unscii-8.hex",
	"packages/natives/native/index.js",
	"packages/natives/native/clipboard.js",
	"packages/natives/native/desktop.js",
	// Provider instruction, payload, and final tool-contract transforms.
	"packages/ai/src/api-registry.ts",
	"packages/ai/package.json",
	"packages/ai/src/index.ts",
	"packages/ai/src/auth-gateway/index.ts",
	"packages/ai/src/auth-gateway/server.ts",
	"packages/ai/src/context-instructions.ts",
	"packages/ai/src/dialect/**/*.md",
	"packages/ai/src/dialect/**/*.ts",
	"packages/ai/src/error/**/*.ts",
	"packages/ai/src/providers/**/*.md",
	"packages/ai/src/providers/**/*.ts",
	"packages/ai/src/registry/amazon-bedrock.ts",
	"packages/ai/src/registry/api-key-login.ts",
	"packages/ai/src/registry/api-key-validation.ts",
	"packages/ai/src/registry/bedrock-mantle.ts",
	"packages/ai/src/registry/index.ts",
	"packages/ai/src/registry/derived.ts",
	"packages/ai/src/registry/registry.ts",
	"packages/ai/src/registry/types.ts",
	"packages/ai/src/registry/oauth/oauth.html",
	"packages/ai/src/stream.ts",
	"packages/ai/src/types.ts",
	"packages/ai/src/utils/anthropic-auth.ts",
	"packages/ai/src/utils/abort.ts",
	"packages/ai/src/utils/block-symbols.ts",
	"packages/ai/src/utils/deterministic-id.ts",
	"packages/ai/src/utils/empty-completion-retry.ts",
	"packages/ai/src/utils/event-stream.ts",
	"packages/ai/src/utils/google-validation.ts",
	"packages/ai/src/utils/harmony-leak.ts",
	"packages/ai/src/utils/http-inspector.ts",
	"packages/ai/src/utils/idle-iterator.ts",
	"packages/ai/src/utils/leaked-thinking-stream.ts",
	"packages/ai/src/utils/openai-http.ts",
	"packages/ai/src/utils/provider-response.ts",
	"packages/ai/src/utils/proxy.ts",
	"packages/ai/src/utils/retry-after.ts",
	"packages/ai/src/utils/retry.ts",
	"packages/ai/src/utils/sdk-stream-timeout.ts",
	"packages/ai/src/utils/stream-markup-healing.ts",
	"packages/ai/src/utils/thinking-loop.ts",
	"packages/ai/src/utils/tool-call-loop-guard.ts",
	"packages/ai/src/utils/tool-choice.ts",
	"packages/ai/src/utils.ts",
	"packages/ai/src/utils/schema/**/*.ts",
	"packages/ai/src/utils/validation.ts",
	// Model identity and wire-compatibility inputs.
	"packages/catalog/src/build.ts",
	"packages/catalog/src/compat/**/*.ts",
	"packages/catalog/src/discovery/**/*.ts",
	"packages/catalog/src/effort.ts",
	"packages/catalog/src/fireworks-model-id.ts",
	"packages/catalog/src/hosts.ts",
	"packages/catalog/src/identity/**/*.ts",
	"packages/catalog/src/index.ts",
	"packages/catalog/src/model-cache.ts",
	"packages/catalog/src/model-manager.ts",
	"packages/catalog/src/model-thinking.ts",
	"packages/catalog/src/models.json",
	"packages/catalog/src/models.ts",
	"packages/catalog/src/provider-models/**/*.ts",
	"packages/catalog/src/utils.ts",
	"packages/catalog/src/variant-collapse.ts",
	"packages/catalog/src/wire/**/*.ts",
	// Mnemopi memory ranking, clipping, and model-context formatting.
	"packages/mnemopi/src/index.ts",
	"packages/mnemopi/src/core/index.ts",
	"packages/mnemopi/src/config.ts",
	"packages/mnemopi/src/core/banks.ts",
	"packages/mnemopi/src/core/embeddings.ts",
	"packages/mnemopi/src/core/memory.ts",
	// Direct-user template expansion and conditional tool catalog construction.
	"packages/coding-agent/src/advisor/advise-tool.ts",
	"packages/coding-agent/src/advisor/config.ts",
	"packages/coding-agent/src/advisor/delta-split.ts",
	"packages/coding-agent/src/advisor/emission-guard.ts",
	"packages/coding-agent/src/advisor/runtime.ts",
	"packages/coding-agent/src/advisor/watchdog.ts",
	"packages/coding-agent/src/auto-thinking/classifier.ts",
	"packages/coding-agent/src/config/inline-tool-descriptors-mode.ts",
	"packages/coding-agent/src/config/model-registry.ts",
	"packages/coding-agent/src/config/model-resolver.ts",
	"packages/coding-agent/src/config/model-roles.ts",
	"packages/coding-agent/src/config/prompt-templates.ts",
	"packages/coding-agent/src/config/service-tier.ts",
	"packages/coding-agent/src/context/implementation-sources.ts",
	"packages/coding-agent/src/context/prompt-sources.generated.ts",
	"packages/coding-agent/src/context/registry.ts",
	"packages/coding-agent/src/context/smarty-skills.ts",
	"packages/coding-agent/src/context/tool-contracts.ts",
	"packages/coding-agent/src/cursor-bridge-tools.ts",
	"packages/coding-agent/src/cursor.ts",
	"packages/coding-agent/src/capability/**/*.ts",
	"packages/coding-agent/src/config/append-only-context-mode.ts",
	"packages/coding-agent/src/config/provider-globals.ts",
	"packages/coding-agent/src/config/settings-schema.ts",
	"packages/coding-agent/src/config/settings.ts",
	// External instruction and extension discovery, filtering, and guarded injection.
	"packages/coding-agent/src/discovery/**/*.ts",
	"packages/coding-agent/src/dap/client.ts",
	"packages/coding-agent/src/dap/config.ts",
	"packages/coding-agent/src/dap/defaults.json",
	"packages/coding-agent/src/dap/index.ts",
	"packages/coding-agent/src/dap/session.ts",
	"packages/coding-agent/src/edit/**/*.{lark,ts}",
	"packages/coding-agent/src/extensibility/custom-commands/bundled/**/*.ts",
	"packages/coding-agent/src/extensibility/custom-commands/loader.ts",
	"packages/coding-agent/src/extensibility/custom-tools/loader.ts",
	"packages/coding-agent/src/extensibility/custom-tools/index.ts",
	"packages/coding-agent/src/extensibility/custom-tools/wrapper.ts",
	"packages/coding-agent/src/extensibility/extensions/compact-handler.ts",
	"packages/coding-agent/src/extensibility/extensions/index.ts",
	"packages/coding-agent/src/extensibility/extensions/loader.ts",
	"packages/coding-agent/src/extensibility/extensions/model-api.ts",
	"packages/coding-agent/src/extensibility/extensions/runner.ts",
	"packages/coding-agent/src/extensibility/extensions/types.ts",
	"packages/coding-agent/src/extensibility/extensions/wrapper.ts",
	"packages/coding-agent/src/extensibility/hooks/loader.ts",
	"packages/coding-agent/src/extensibility/hooks/runner.ts",
	"packages/coding-agent/src/extensibility/hooks/tool-wrapper.ts",
	"packages/coding-agent/src/extensibility/legacy-pi-ai-shim.ts",
	"packages/coding-agent/src/extensibility/legacy-pi-coding-agent-shim.ts",
	"packages/coding-agent/src/extensibility/legacy-typebox.ts",
	"packages/coding-agent/src/extensibility/plugins/legacy-pi-compat.ts",
	"packages/coding-agent/src/extensibility/plugins/loader.ts",
	"packages/coding-agent/src/extensibility/plugins/runtime-config.ts",
	"packages/coding-agent/src/extensibility/skills.ts",
	"packages/coding-agent/src/extensibility/slash-commands.ts",
	"packages/coding-agent/src/extensibility/tool-event-input.ts",
	"packages/coding-agent/src/extensibility/tool-proxy.ts",
	// Goal/todo authority and automatic-turn producers.
	"packages/coding-agent/src/goals/**/*.ts",
	"packages/coding-agent/src/hindsight/backend.ts",
	"packages/coding-agent/src/hindsight/bank.ts",
	"packages/coding-agent/src/hindsight/config.ts",
	"packages/coding-agent/src/hindsight/client.ts",
	"packages/coding-agent/src/hindsight/content.ts",
	"packages/coding-agent/src/hindsight/mental-models.ts",
	"packages/coding-agent/src/hindsight/seeds.json",
	"packages/coding-agent/src/hindsight/state.ts",
	"packages/coding-agent/src/hindsight/transcript.ts",
	"packages/coding-agent/src/internal-urls/**/*.ts",
	"packages/coding-agent/src/irc/bus.ts",
	"packages/coding-agent/src/launch/**/*.ts",
	"packages/coding-agent/src/lsp/**/*.{json,lark,ts}",
	"packages/coding-agent/src/lib/xai-http.ts",
	// Exact MCP instructions and tool contracts, including cached/deferred definitions.
	"packages/coding-agent/src/mcp/client.ts",
	"packages/coding-agent/src/mcp/config.ts",
	"packages/coding-agent/src/mcp/index.ts",
	"packages/coding-agent/src/mcp/loader.ts",
	"packages/coding-agent/src/mcp/manager.ts",
	"packages/coding-agent/src/mcp/json-rpc.ts",
	"packages/coding-agent/src/mcp/request-id.ts",
	"packages/coding-agent/src/mcp/timeout.ts",
	"packages/coding-agent/src/mcp/tool-cache.ts",
	"packages/coding-agent/src/mcp/tool-bridge.ts",
	"packages/coding-agent/src/mcp/transports/**/*.ts",
	"packages/coding-agent/src/mcp/types.ts",
	"packages/coding-agent/src/memories/index.ts",
	"packages/coding-agent/src/memory-backend/local-backend.ts",
	"packages/coding-agent/src/memory-backend/index.ts",
	"packages/coding-agent/src/memory-backend/messages.ts",
	"packages/coding-agent/src/memory-backend/off-backend.ts",
	"packages/coding-agent/src/memory-backend/resolve.ts",
	"packages/coding-agent/src/memory-backend/runtime.ts",
	"packages/coding-agent/src/memory-backend/tool-names.ts",
	"packages/coding-agent/src/mnemopi/backend.ts",
	"packages/coding-agent/src/mnemopi/config.ts",
	"packages/coding-agent/src/mnemopi/embed-client.ts",
	"packages/coding-agent/src/mnemopi/embed-protocol.ts",
	"packages/coding-agent/src/mnemopi/embed-worker.ts",
	"packages/coding-agent/src/mnemopi/state.ts",
	"packages/coding-agent/src/markit/**/*.ts",
	// Registered prompt request builders and side-model transforms.
	"packages/coding-agent/src/async/job-manager.ts",
	"packages/coding-agent/src/async/index.ts",
	"packages/coding-agent/src/autolearn/controller.ts",
	"packages/coding-agent/src/autolearn/managed-skills.ts",
	"packages/coding-agent/src/autoresearch/git.ts",
	"packages/coding-agent/src/autoresearch/helpers.ts",
	"packages/coding-agent/src/autoresearch/index.ts",
	"packages/coding-agent/src/autoresearch/state.ts",
	"packages/coding-agent/src/autoresearch/storage.ts",
	"packages/coding-agent/src/autoresearch/tools/**/*.ts",
	"packages/coding-agent/src/cleanse/agent.ts",
	"packages/coding-agent/src/cleanse/balance.ts",
	"packages/coding-agent/src/cleanse/checkers.ts",
	"packages/coding-agent/src/cleanse/index.ts",
	"packages/coding-agent/src/cleanse/loop.ts",
	"packages/coding-agent/src/cleanse/parsers.ts",
	"packages/coding-agent/src/cli/auth-gateway-cli.ts",
	"packages/coding-agent/src/cli/args.ts",
	"packages/coding-agent/src/cli/agents-cli.ts",
	"packages/coding-agent/src/cli/auth-broker-cli.ts",
	"packages/coding-agent/src/cli/bench-cli.ts",
	"packages/coding-agent/src/cli/classify-install-target.ts",
	"packages/coding-agent/src/cli/config-cli.ts",
	"packages/coding-agent/src/cli/dry-balance-cli.ts",
	"packages/coding-agent/src/cli/extension-flags.ts",
	"packages/coding-agent/src/cli/file-processor.ts",
	"packages/coding-agent/src/cli/initial-message.ts",
	"packages/coding-agent/src/cli/models-cli.ts",
	"packages/coding-agent/src/cli/plugin-cli.ts",
	"packages/coding-agent/src/cli/session-picker.ts",
	"packages/coding-agent/src/cli/cleanse-picker.ts",
	"packages/coding-agent/src/cli/setup-cli.ts",
	"packages/coding-agent/src/cli/ssh-cli.ts",
	"packages/coding-agent/src/cli/usage-cli.ts",
	"packages/coding-agent/src/collab/host.ts",
	"packages/coding-agent/src/commit/agentic/agent.ts",
	"packages/coding-agent/src/commit/agentic/tools/**/*.ts",
	"packages/coding-agent/src/commit/analysis/**/*.ts",
	"packages/coding-agent/src/commit/changelog/**/*.ts",
	"packages/coding-agent/src/commit/cli.ts",
	"packages/coding-agent/src/commit/index.ts",
	"packages/coding-agent/src/commit/map-reduce/**/*.ts",
	"packages/coding-agent/src/commit/pipeline.ts",
	"packages/coding-agent/src/commit/agentic/fallback.ts",
	"packages/coding-agent/src/commit/agentic/index.ts",
	"packages/coding-agent/src/commit/agentic/lock-files.ts",
	"packages/coding-agent/src/commit/agentic/topo-sort.ts",
	"packages/coding-agent/src/commit/agentic/trivial.ts",
	"packages/coding-agent/src/commit/agentic/validation.ts",
	"packages/coding-agent/src/commit/git/diff.ts",
	"packages/coding-agent/src/commit/model-selection.ts",
	"packages/coding-agent/src/commit/shared-llm.ts",
	"packages/coding-agent/src/commit/utils.ts",
	"packages/coding-agent/src/commit/utils/exclusions.ts",
	"packages/coding-agent/src/compress/index.ts",
	"packages/coding-agent/src/compress/protocol.ts",
	"packages/coding-agent/src/compress/session.ts",
	"packages/coding-agent/src/eval/completion-bridge.ts",
	"packages/coding-agent/src/eval/**/*.{jl,py,rb,ts,txt}",
	"packages/coding-agent/src/exa/mcp-client.ts",
	"packages/coding-agent/src/exec/bash-executor.ts",
	"packages/coding-agent/src/exec/direnv.ts",
	"packages/coding-agent/src/exec/non-interactive-env.ts",
	"packages/coding-agent/src/export/ttsr.ts",
	"packages/coding-agent/src/live/controller.ts",
	"packages/coding-agent/src/live/protocol.ts",
	"packages/coding-agent/src/live/transport.ts",
	"packages/coding-agent/src/modes/acp/acp-agent.ts",
	"packages/coding-agent/src/modes/acp/acp-client-bridge.ts",
	"packages/coding-agent/src/modes/acp/acp-mode.ts",
	"packages/coding-agent/src/modes/fresh-omp-companion.ts",
	"packages/coding-agent/src/modes/fresh-omp-companion-wire.ts",
	"packages/coding-agent/src/modes/emoji-autocomplete.ts",
	"packages/coding-agent/src/modes/data/emojis.json",
	"packages/coding-agent/src/modes/components/agents-hub.ts",
	"packages/coding-agent/src/modes/components/agent-hub.ts",
	"packages/coding-agent/src/modes/components/agent-hub-projection.ts",
	"packages/coding-agent/src/modes/components/agent-transcript-viewer.ts",
	"packages/coding-agent/src/modes/components/advisor-config.ts",
	"packages/coding-agent/src/modes/components/ask-dialog.ts",
	"packages/coding-agent/src/modes/components/countdown-timer.ts",
	"packages/coding-agent/src/modes/components/custom-editor.ts",
	"packages/coding-agent/src/modes/components/extensions/extension-dashboard.ts",
	"packages/coding-agent/src/modes/components/extensions/extension-list.ts",
	"packages/coding-agent/src/modes/components/extensions/state-manager.ts",
	"packages/coding-agent/src/modes/components/extensions/types.ts",
	"packages/coding-agent/src/modes/components/mcp-add-wizard.ts",
	"packages/coding-agent/src/modes/components/model-browser.ts",
	"packages/coding-agent/src/modes/components/model-hub.ts",
	"packages/coding-agent/src/modes/components/model-picker.ts",
	"packages/coding-agent/src/modes/components/oauth-selector.ts",
	"packages/coding-agent/src/modes/components/history-search.ts",
	"packages/coding-agent/src/modes/components/hook-editor.ts",
	"packages/coding-agent/src/modes/components/hook-input.ts",
	"packages/coding-agent/src/modes/components/hook-selector.ts",
	"packages/coding-agent/src/modes/components/logout-account-selector.ts",
	"packages/coding-agent/src/modes/components/plan-review-overlay.ts",
	"packages/coding-agent/src/modes/components/plan-toc.ts",
	"packages/coding-agent/src/modes/components/plugin-selector.ts",
	"packages/coding-agent/src/modes/components/plugin-settings.ts",
	"packages/coding-agent/src/modes/components/reset-usage-selector.ts",
	"packages/coding-agent/src/modes/components/session-account-selector.ts",
	"packages/coding-agent/src/modes/components/session-selector.ts",
	"packages/coding-agent/src/modes/components/settings-selector.ts",
	"packages/coding-agent/src/modes/components/settings-defs.ts",
	"packages/coding-agent/src/modes/components/tree-selector.ts",
	"packages/coding-agent/src/modes/components/user-message-selector.ts",
	"packages/coding-agent/src/modes/controllers/input-controller.ts",
	"packages/coding-agent/src/modes/controllers/btw-controller.ts",
	"packages/coding-agent/src/modes/controllers/command-controller.ts",
	"packages/coding-agent/src/modes/controllers/command-controller-shared.ts",
	"packages/coding-agent/src/modes/controllers/event-controller.ts",
	"packages/coding-agent/src/modes/controllers/extension-ui-controller.ts",
	"packages/coding-agent/src/modes/controllers/live-command-controller.ts",
	"packages/coding-agent/src/modes/controllers/mcp-command-controller.ts",
	"packages/coding-agent/src/modes/controllers/omfg-controller.ts",
	"packages/coding-agent/src/modes/controllers/omfg-rule.ts",
	"packages/coding-agent/src/modes/controllers/selector-controller.ts",
	"packages/coding-agent/src/modes/controllers/session-focus-controller.ts",
	"packages/coding-agent/src/modes/controllers/ssh-command-controller.ts",
	"packages/coding-agent/src/modes/controllers/tan-command-controller.ts",
	"packages/coding-agent/src/modes/controllers/todo-command-controller.ts",
	"packages/coding-agent/src/modes/interactive-mode.ts",
	"packages/coding-agent/src/modes/loop-limit.ts",
	"packages/coding-agent/src/modes/orchestrate.ts",
	"packages/coding-agent/src/modes/print-mode.ts",
	"packages/coding-agent/src/modes/rpc/host-tools.ts",
	"packages/coding-agent/src/modes/rpc/rpc-mode.ts",
	"packages/coding-agent/src/modes/skill-command.ts",
	"packages/coding-agent/src/modes/ultrathink.ts",
	"packages/coding-agent/src/modes/utils/ui-helpers.ts",
	"packages/coding-agent/src/modes/utils/context-usage.ts",
	"packages/coding-agent/src/modes/workflow.ts",
	"packages/coding-agent/src/priority.json",
	"packages/coding-agent/src/registry/**/*.ts",
	"packages/coding-agent/src/plan-mode/approved-plan.ts",
	"packages/coding-agent/src/plan-mode/model-transition.ts",
	"packages/coding-agent/src/plan-mode/plan-files.ts",
	"packages/coding-agent/src/plan-mode/plan-handoff.ts",
	"packages/coding-agent/src/plan-mode/plan-protection.ts",
	"packages/coding-agent/src/security/coordinator.ts",
	"packages/coding-agent/src/security/auth.ts",
	"packages/coding-agent/src/security/cloud.ts",
	"packages/coding-agent/src/security/comparison.ts",
	"packages/coding-agent/src/security/contracts/ids.ts",
	"packages/coding-agent/src/security/contracts/index.ts",
	"packages/coding-agent/src/security/contracts/schemas.ts",
	"packages/coding-agent/src/security/contracts/validation.ts",
	"packages/coding-agent/src/security/importers/codex-security.ts",
	"packages/coding-agent/src/security/importers/index.ts",
	"packages/coding-agent/src/security/importers/sarif.ts",
	"packages/coding-agent/src/security/preflight.ts",
	"packages/coding-agent/src/security/provenance.ts",
	"packages/coding-agent/src/security/publication.ts",
	"packages/coding-agent/src/security/resource-output.ts",
	"packages/coding-agent/src/security/sarif.ts",
	"packages/coding-agent/src/security/store.ts",
	"packages/coding-agent/src/sdk.ts",
	"packages/coding-agent/src/cli.ts",
	"packages/coding-agent/src/cli-commands.ts",
	"packages/coding-agent/src/cli/flag-tables.ts",
	"packages/coding-agent/src/cli/profile-bootstrap.ts",
	"packages/coding-agent/src/cli/startup-cwd.ts",
	"packages/coding-agent/src/commands/acp.ts",
	"packages/coding-agent/src/commands/agents.ts",
	"packages/coding-agent/src/commands/auth-broker.ts",
	"packages/coding-agent/src/commands/auth-gateway.ts",
	"packages/coding-agent/src/commands/bench.ts",
	"packages/coding-agent/src/commands/cleanse.ts",
	"packages/coding-agent/src/commands/collab-bridge.ts",
	"packages/coding-agent/src/commands/commit.ts",
	"packages/coding-agent/src/commands/compress.ts",
	"packages/coding-agent/src/commands/config.ts",
	"packages/coding-agent/src/commands/dry-balance.ts",
	"packages/coding-agent/src/commands/install.ts",
	"packages/coding-agent/src/commands/join.ts",
	"packages/coding-agent/src/commands/launch.ts",
	"packages/coding-agent/src/commands/models.ts",
	"packages/coding-agent/src/commands/plugin.ts",
	"packages/coding-agent/src/commands/setup.ts",
	"packages/coding-agent/src/commands/ssh.ts",
	"packages/coding-agent/src/commands/usage.ts",
	"packages/coding-agent/src/main.ts",
	"packages/coding-agent/src/secrets/**/*.ts",
	"packages/coding-agent/src/session/async-job-delivery.ts",
	"packages/coding-agent/src/session/acp-permission-gate.ts",
	"packages/coding-agent/src/session/agent-session.ts",
	"packages/coding-agent/src/session/automatic-turn-authority.ts",
	"packages/coding-agent/src/session/bash-runner.ts",
	"packages/coding-agent/src/session/blob-store.ts",
	"packages/coding-agent/src/session/checkpoint-entries.ts",
	"packages/coding-agent/src/session/claude-session-store.ts",
	"packages/coding-agent/src/session/compact-modes.ts",
	"packages/coding-agent/src/session/codex-session-store.ts",
	"packages/coding-agent/src/session/eval-runner.ts",
	"packages/coding-agent/src/session/execution-environment.ts",
	"packages/coding-agent/src/session/exit-diagnostics.ts",
	"packages/coding-agent/src/session/foreign-session-import.ts",
	"packages/coding-agent/src/session/foreign-session-jsonl.ts",
	"packages/coding-agent/src/session/irc-bridge.ts",
	"packages/coding-agent/src/session/launch-completion.ts",
	"packages/coding-agent/src/session/messages.ts",
	"packages/coding-agent/src/session/model-controls.ts",
	"packages/coding-agent/src/session/prewalk.ts",
	"packages/coding-agent/src/session/provider-image-budget.ts",
	"packages/coding-agent/src/session/queued-messages.ts",
	"packages/coding-agent/src/session/retry-fallback-chains.ts",
	"packages/coding-agent/src/session/role-models.ts",
	"packages/coding-agent/src/session/session-advisors.ts",
	"packages/coding-agent/src/session/session-context.ts",
	"packages/coding-agent/src/session/session-stats.ts",
	"packages/coding-agent/src/session/session-entries.ts",
	"packages/coding-agent/src/session/session-handoff.ts",
	"packages/coding-agent/src/session/session-history-format.ts",
	"packages/coding-agent/src/session/session-loader.ts",
	"packages/coding-agent/src/session/session-lifecycle-owner.ts",
	"packages/coding-agent/src/session/session-lifecycle-transaction.ts",
	"packages/coding-agent/src/session/session-maintenance.ts",
	"packages/coding-agent/src/session/session-manager.ts",
	"packages/coding-agent/src/session/session-memory.ts",
	"packages/coding-agent/src/session/session-migrations.ts",
	"packages/coding-agent/src/session/session-persistence.ts",
	"packages/coding-agent/src/session/session-provider-boundary.ts",
	"packages/coding-agent/src/session/settings-stream-fn.ts",
	"packages/coding-agent/src/session/snapcompact-inline.ts",
	"packages/coding-agent/src/session/session-tools.ts",
	"packages/coding-agent/src/session/session-workspace.ts",
	"packages/coding-agent/src/session/stream-guards.ts",
	"packages/coding-agent/src/session/streaming-output.ts",
	"packages/coding-agent/src/session/todo-tracker.ts",
	"packages/coding-agent/src/session/tool-choice-queue.ts",
	"packages/coding-agent/src/session/ttsr-coordinator.ts",
	"packages/coding-agent/src/session/turn-recovery.ts",
	"packages/coding-agent/src/session/turn-persistence.ts",
	"packages/coding-agent/src/session/unexpected-stop-classifier.ts",
	"packages/coding-agent/src/session/yield-queue.ts",
	"packages/coding-agent/src/system-prompt.ts",
	"packages/coding-agent/src/subprocess/worker-client.ts",
	"packages/coding-agent/src/subprocess/worker-runtime.ts",
	"packages/coding-agent/src/task/**/*.ts",
	"packages/coding-agent/src/thinking.ts",
	"packages/coding-agent/src/stt/asr-worker.ts",
	"packages/coding-agent/src/stt/stt-controller.ts",
	"packages/coding-agent/src/tiny/models.ts",
	"packages/coding-agent/src/tiny/message-preproc.ts",
	"packages/coding-agent/src/tiny/device.ts",
	"packages/coding-agent/src/tiny/dtype.ts",
	"packages/coding-agent/src/tiny/title-client.ts",
	"packages/coding-agent/src/tiny/title-protocol.ts",
	"packages/coding-agent/src/tiny/worker.ts",
	"packages/coding-agent/src/tools/**/*.ts",
	"packages/coding-agent/src/tts/speech-enhancer.ts",
	"packages/coding-agent/src/tts/models.ts",
	"packages/coding-agent/src/tts/tts-client.ts",
	"packages/coding-agent/src/tts/tts-protocol.ts",
	"packages/coding-agent/src/tts/tts-worker.ts",
	"packages/coding-agent/src/tts/wav.ts",
	"packages/coding-agent/src/utils/active-repo-context.ts",
	"packages/coding-agent/src/utils/block-context.ts",
	"packages/coding-agent/src/utils/command-args.ts",
	"packages/coding-agent/src/utils/commit-message-generator.ts",
	"packages/coding-agent/src/utils/cpuprofile.ts",
	"packages/coding-agent/src/utils/edit-mode.ts",
	"packages/coding-agent/src/utils/file-display-mode.ts",
	"packages/coding-agent/src/utils/image-loading.ts",
	"packages/coding-agent/src/utils/image-resize.ts",
	"packages/coding-agent/src/utils/image-vision-fallback.ts",
	"packages/coding-agent/src/utils/inspect-image-mode.ts",
	"packages/coding-agent/src/utils/ipc.ts",
	"packages/coding-agent/src/utils/local-date.ts",
	"packages/coding-agent/src/utils/mac-file-urls.applescript",
	"packages/coding-agent/src/utils/markit-cache.ts",
	"packages/coding-agent/src/utils/markit.ts",
	"packages/coding-agent/src/utils/profile-tree.ts",
	"packages/coding-agent/src/utils/prompt-path.ts",
	"packages/coding-agent/src/utils/sample-profile.ts",
	"packages/coding-agent/src/utils/shell-snapshot-fn-env.sh",
	"packages/coding-agent/src/utils/title-generator.ts",
	"packages/coding-agent/src/utils/turndown.ts",
	"packages/coding-agent/src/utils/tool-choice.ts",
	"packages/coding-agent/src/utils/zip.ts",
	"packages/coding-agent/src/config.ts",
	"packages/coding-agent/src/config/claude-paths.ts",
	"packages/coding-agent/src/config/config-file.ts",
	"packages/coding-agent/src/slash-commands/acp-builtins.ts",
	"packages/coding-agent/src/slash-commands/builtin-control.ts",
	"packages/coding-agent/src/slash-commands/builtin-modes.ts",
	"packages/coding-agent/src/slash-commands/builtin-registry.ts",
	"packages/coding-agent/src/slash-commands/helpers/active-oauth-account.ts",
	"packages/coding-agent/src/slash-commands/helpers/logout.ts",
	"packages/coding-agent/src/slash-commands/helpers/marketplace-manager.ts",
	"packages/coding-agent/src/slash-commands/helpers/mcp.ts",
	"packages/coding-agent/src/slash-commands/helpers/parse.ts",
	"packages/coding-agent/src/slash-commands/helpers/reset-usage.ts",
	"packages/coding-agent/src/slash-commands/helpers/security.ts",
	"packages/coding-agent/src/slash-commands/helpers/session-pin.ts",
	"packages/coding-agent/src/slash-commands/helpers/ssh.ts",
	"packages/coding-agent/src/slash-commands/helpers/todo.ts",
	"packages/coding-agent/src/modes/setup-wizard/scenes/model.ts",
	"packages/coding-agent/src/modes/setup-version.ts",
	"packages/coding-agent/src/modes/setup-wizard/index.ts",
	"packages/coding-agent/src/modes/setup-wizard/scenes/providers.ts",
	"packages/coding-agent/src/modes/setup-wizard/scenes/sign-in.ts",
	"packages/coding-agent/src/modes/setup-wizard/scenes/web-search.ts",
	"packages/coding-agent/src/mcp/oauth-discovery.ts",
	"packages/coding-agent/src/ssh/config-writer.ts",
	"packages/coding-agent/src/collab/local-transport.ts",
	"packages/coding-agent/src/utils/fetch-timeout.ts",
	"packages/coding-agent/scripts/generate-docs-index.ts",
	"packages/coding-agent/scripts/compile-binary.ts",
	"packages/coding-agent/scripts/bundle-dist.ts",
	"packages/coding-agent/src/vibe/runtime.ts",
	"packages/coding-agent/src/web/parallel.ts",
	"packages/coding-agent/src/web/scrapers/**/*.ts",
	"packages/coding-agent/src/web/search/**/*.{lark,ts}",
	"packages/coding-agent/src/workspace-tree.ts",
] as const;

const IMPLEMENTATION_SOURCE_EXCLUSIONS = new Set([
	"packages/agent/src/utils/yield.ts",
	"packages/ai/src/utils/schema/CONSTRAINTS.md",
	"packages/ai/src/utils/request-debug.ts",
	"packages/ai/src/utils/sse-debug.ts",
	"packages/ai/src/providers/google-types.ts",
	"packages/ai/src/dialect/types.ts",
	"packages/hashline/src/types.ts",
	"packages/omptype/src/infer.ts",
	"packages/mnemopi/src/core/beam/types.ts",
	"packages/mnemopi/src/diagnose.ts",
	"packages/coding-agent/src/advisor/transcript-recorder.ts",
	"packages/coding-agent/src/autoresearch/dashboard.ts",
	"packages/coding-agent/src/cleanse/types.ts",
	"packages/coding-agent/src/commit/agentic/state.ts",
	"packages/coding-agent/src/capability/types.ts",
	"packages/coding-agent/src/config/keybindings.ts",
	"packages/coding-agent/src/extensibility/custom-tools/types.ts",
	"packages/coding-agent/src/eval/types.ts",
	"packages/coding-agent/src/internal-urls/types.ts",
	"packages/coding-agent/src/markit/types.ts",
	"packages/coding-agent/src/dap/types.ts",
	"packages/coding-agent/src/plan-mode/state.ts",
	"packages/coding-agent/src/modes/acp/acp-event-mapper.ts",
	"packages/coding-agent/src/modes/acp/terminal-auth.ts",
	"packages/coding-agent/src/modes/github-ref-autocomplete.ts",
	"packages/coding-agent/src/modes/gradient-highlight.ts",
	"packages/coding-agent/src/modes/internal-url-autocomplete.ts",
	"packages/coding-agent/src/modes/magic-keywords.ts",
	"packages/coding-agent/src/modes/components/todo-reminder.ts",
	"packages/coding-agent/src/modes/oauth-manual-input.ts",
	"packages/coding-agent/src/modes/prompt-action-autocomplete.ts",
	"packages/coding-agent/src/modes/running-subagent-badge.ts",
	"packages/coding-agent/src/modes/rpc/rpc-frame.ts",
	"packages/coding-agent/src/modes/rpc/rpc-messages.ts",
	"packages/coding-agent/src/modes/rpc/rpc-subagents.ts",
	"packages/coding-agent/src/modes/session-observer-registry.ts",
	"packages/coding-agent/src/modes/shared.ts",
	"packages/coding-agent/src/modes/warp-events.ts",
	"packages/coding-agent/src/session/session-title-slot.ts",
	"packages/coding-agent/src/session/snapcompact-savings-journal.ts",
	"packages/coding-agent/src/stt/asr-protocol.ts",
	"packages/coding-agent/src/eval/js/worker-protocol.ts",
	"packages/coding-agent/src/eval/js/shared/types.ts",
	"packages/coding-agent/generated/prompt-manifest.json",
	"packages/coding-agent/src/mnemopi/embed-protocol.ts",
	"packages/coding-agent/src/tiny/title-protocol.ts",
	"packages/coding-agent/src/tools/browser/tab-protocol.ts",
	"packages/coding-agent/src/tts/tts-protocol.ts",
	"packages/coding-agent/src/mcp/render.ts",
	"packages/coding-agent/src/lsp/render.ts",
	"packages/coding-agent/src/task/render.ts",
	"packages/coding-agent/src/task/renderer.ts",
	"packages/coding-agent/src/web/search/render.ts",
	"packages/coding-agent/src/tools/browser/render.ts",
	"packages/coding-agent/src/tools/browser/relay/protocol.ts",
	"packages/coding-agent/src/tools/computer-renderer.ts",
	"packages/coding-agent/src/tools/default-renderer.ts",
	"packages/coding-agent/src/tools/eval-render.ts",
	"packages/coding-agent/src/tools/gh-renderer.ts",
	"packages/coding-agent/src/tools/gh-types.ts",
	"packages/coding-agent/src/tools/inspect-image-renderer.ts",
	"packages/coding-agent/src/tools/json-tree.ts",
	"packages/coding-agent/src/tools/memory-render.ts",
	"packages/coding-agent/src/tools/read-renderer.ts",
	"packages/coding-agent/src/tools/renderers.ts",
	"packages/coding-agent/src/tools/eval-format/index.ts",
	"packages/coding-agent/src/tools/eval-format/javascript.ts",
	"packages/coding-agent/src/tools/eval-format/julia.ts",
	"packages/coding-agent/src/tools/eval-format/python.ts",
	"packages/coding-agent/src/tools/eval-format/ruby.ts",
	"packages/coding-agent/src/tts/runtime.ts",
	"packages/coding-agent/src/tts/speakable.ts",
	"packages/coding-agent/src/tts/streaming-player.ts",
	"packages/coding-agent/src/tts/vocalizer.ts",
	"packages/coding-agent/src/telemetry-export.ts",
	"packages/coding-agent/src/utils/changelog.ts",
	"packages/coding-agent/src/utils/late-cleanup.ts",
	"packages/coding-agent/src/utils/open.ts",
	"packages/coding-agent/src/utils/session-color.ts",
	"packages/coding-agent/src/utils/sixel.ts",
	"packages/coding-agent/src/utils/thinking-display.ts",
	"packages/coding-agent/src/utils/token-rate.ts",
	"packages/utils/src/logger.ts",
	"packages/utils/src/logger/rotating-file.ts",
	"packages/utils/src/process-name.ts",
	"packages/utils/src/stderr-guard.ts",
	"packages/utils/src/timing-buffer.ts",
]);

const IMPLEMENTATION_SOURCE_EXCLUDED_PREFIXES = [
	"packages/coding-agent/src/cli/",
	"packages/coding-agent/src/commands/",
	"packages/coding-agent/src/debug/",
	"packages/coding-agent/src/export/",
	"packages/coding-agent/src/modes/components/",
	"packages/coding-agent/src/modes/controllers/",
	"packages/coding-agent/src/modes/setup-wizard/",
	"packages/coding-agent/src/modes/theme/",
	"packages/coding-agent/src/modes/utils/",
	"packages/coding-agent/src/slash-commands/helpers/",
	"packages/coding-agent/src/tui/",
] as const;

const IMPLEMENTATION_SOURCE_NO_TRANSITIVE_IMPORTS = new Set([
	"packages/agent/src/index.ts",
	"packages/ai/src/index.ts",
	"packages/catalog/src/index.ts",
	"packages/coding-agent/src/async/index.ts",
	"packages/coding-agent/src/extensibility/custom-tools/index.ts",
	"packages/coding-agent/src/extensibility/extensions/index.ts",
	"packages/coding-agent/src/main.ts",
	"packages/coding-agent/src/mcp/index.ts",
	"packages/coding-agent/src/memory-backend/index.ts",
	"packages/utils/src/index.ts",
]);

const implementationSourceTranspiler = new Bun.Transpiler({ loader: "ts" });
const REEXPORT_ONLY_PATTERN = /export\s+(?:type\s+)?(?:\*\s*(?:as\s+\w+\s*)?|\{[^}]*\})\s+from\s+["'][^"']+["']\s*;?/g;

interface WorkspacePackage {
	root: string;
	manifest: Record<string, unknown>;
}

const EXCLUDED_WORKSPACE_PACKAGES = new Set(["@oh-my-pi/omp-stats", "@oh-my-pi/pi-natives", "@oh-my-pi/pi-tui"]);

const EXCLUDED_WORKSPACE_IMPORTS = new Set(["@oh-my-pi/pi-utils/chalk"]);

/** Runtime imports only: Bun drops type-only edges and this strips re-export-only barrel edges. */
export function runtimeImportSpecifiersForImplementationSource(source: string): readonly string[] {
	return implementationSourceTranspiler
		.scan(source.replaceAll(REEXPORT_ONLY_PATTERN, ""))
		.imports.map(runtimeImport => runtimeImport.path);
}

function isExcludedImplementationDependency(sourcePath: string): boolean {
	return (
		IMPLEMENTATION_SOURCE_EXCLUSIONS.has(sourcePath) ||
		IMPLEMENTATION_SOURCE_EXCLUDED_PREFIXES.some(prefix => sourcePath.startsWith(prefix))
	);
}

async function workspacePackages(repositoryRoot: string): Promise<Map<string, WorkspacePackage>> {
	const packages = new Map<string, WorkspacePackage>();
	for await (const manifestPath of new Bun.Glob("packages/*/package.json").scan({ cwd: repositoryRoot })) {
		const manifest = (await Bun.file(path.join(repositoryRoot, manifestPath)).json()) as Record<string, unknown>;
		if (typeof manifest.name !== "string" || EXCLUDED_WORKSPACE_PACKAGES.has(manifest.name)) continue;
		packages.set(manifest.name, { root: path.posix.dirname(manifestPath), manifest });
	}
	return packages;
}

function runtimeExportTarget(value: unknown): string | undefined {
	if (typeof value === "string") return value;
	if (!value || typeof value !== "object" || Array.isArray(value)) return undefined;
	const conditions = value as Record<string, unknown>;
	return runtimeExportTarget(conditions.import) ?? runtimeExportTarget(conditions.default);
}

function exportedWorkspaceTarget(manifest: Record<string, unknown>, exportKey: string): string | undefined {
	const exports = manifest.exports;
	if (exports && typeof exports === "object" && !Array.isArray(exports)) {
		const entries = exports as Record<string, unknown>;
		const exact = runtimeExportTarget(entries[exportKey]);
		if (exact) return exact;
		const wildcard = Object.entries(entries)
			.filter(([key]) => key.includes("*"))
			.sort(([left], [right]) => right.length - left.length)
			.find(([key]) => {
				const [prefix, suffix = ""] = key.split("*");
				return exportKey.startsWith(prefix) && exportKey.endsWith(suffix);
			});
		if (wildcard) {
			const [key, value] = wildcard;
			const [prefix, suffix = ""] = key.split("*");
			const match = exportKey.slice(prefix.length, exportKey.length - suffix.length);
			return runtimeExportTarget(value)?.replaceAll("*", match);
		}
	}
	if (exportKey !== ".") return undefined;
	return typeof manifest.module === "string"
		? manifest.module
		: typeof manifest.main === "string"
			? manifest.main
			: undefined;
}

async function resolveWorkspaceImport(
	repositoryRoot: string,
	packages: ReadonlyMap<string, WorkspacePackage>,
	specifier: string,
): Promise<string | undefined> {
	if (EXCLUDED_WORKSPACE_IMPORTS.has(specifier)) return undefined;
	const packageName = [...packages.keys()].find(name => specifier === name || specifier.startsWith(`${name}/`));
	if (!packageName) return undefined;
	const workspacePackage = packages.get(packageName)!;
	const suffix = specifier.slice(packageName.length);
	const target = exportedWorkspaceTarget(workspacePackage.manifest, suffix ? `.${suffix}` : ".");
	if (!target) return undefined;
	const sourcePath = path.posix.normalize(path.posix.join(workspacePackage.root, target));
	if (sourcePath.startsWith("../") || sourcePath.includes("/../") || isExcludedImplementationDependency(sourcePath)) {
		return undefined;
	}
	if (sourcePath.endsWith(".md") || !(await Bun.file(path.join(repositoryRoot, sourcePath)).exists()))
		return undefined;
	return sourcePath;
}

async function resolveRuntimeImport(
	repositoryRoot: string,
	packages: ReadonlyMap<string, WorkspacePackage>,
	importerPath: string,
	specifier: string,
): Promise<string | undefined> {
	if (!specifier.startsWith(".")) return await resolveWorkspaceImport(repositoryRoot, packages, specifier);
	const unresolved = path.resolve(repositoryRoot, path.dirname(importerPath), specifier);
	const relative = path.relative(repositoryRoot, unresolved).replaceAll(path.sep, "/");
	if (relative.startsWith("../") || path.isAbsolute(relative)) return undefined;
	const candidates = path.extname(relative)
		? [relative, relative.endsWith(".js") ? `${relative.slice(0, -3)}.ts` : undefined]
		: [
				relative,
				`${relative}.ts`,
				`${relative}.tsx`,
				`${relative}.js`,
				`${relative}.mjs`,
				`${relative}.cjs`,
				`${relative}.json`,
				`${relative}.lark`,
				`${relative}.txt`,
				`${relative}/index.ts`,
				`${relative}/index.js`,
			];
	for (const candidate of candidates) {
		if (!candidate || candidate.endsWith(".md") || isExcludedImplementationDependency(candidate)) continue;
		if (await Bun.file(path.join(repositoryRoot, candidate)).exists()) return candidate;
	}
	return undefined;
}

export async function computeImplementationSources(
	repositoryRoot: string,
): Promise<Array<{ path: string; sha256: string }>> {
	const packages = await workspacePackages(repositoryRoot);
	const paths = new Set<string>();
	const pending: string[] = [];
	for (const pattern of IMPLEMENTATION_SOURCE_GLOBS) {
		for await (const absolutePath of new Bun.Glob(pattern).scan({
			cwd: repositoryRoot,
			absolute: true,
			onlyFiles: true,
		})) {
			const sourcePath = path.relative(repositoryRoot, absolutePath).replaceAll(path.sep, "/");
			if (!IMPLEMENTATION_SOURCE_EXCLUSIONS.has(sourcePath) && !paths.has(sourcePath)) {
				paths.add(sourcePath);
				pending.push(sourcePath);
			}
		}
	}
	while (pending.length > 0) {
		const importerPath = pending.pop();
		if (
			!importerPath ||
			!/\.[cm]?[jt]sx?$/.test(importerPath) ||
			IMPLEMENTATION_SOURCE_NO_TRANSITIVE_IMPORTS.has(importerPath)
		)
			continue;
		const source = await Bun.file(path.join(repositoryRoot, importerPath)).text();
		for (const runtimeImport of runtimeImportSpecifiersForImplementationSource(source)) {
			const dependencyPath = await resolveRuntimeImport(repositoryRoot, packages, importerPath, runtimeImport);
			if (!dependencyPath || paths.has(dependencyPath)) continue;
			paths.add(dependencyPath);
			pending.push(dependencyPath);
		}
	}
	return await Promise.all(
		[...paths]
			.sort((left, right) => left.localeCompare(right))
			.map(async sourcePath => ({
				path: sourcePath,
				sha256: sha256(new Uint8Array(await Bun.file(path.join(repositoryRoot, sourcePath)).arrayBuffer())),
			})),
	);
}
