// Generated by scripts/generate-prompt-manifest.ts. Do not edit.
// biome-ignore-all assist/source/organizeImports: import identifiers are paired with generated mappings.
import source0 from "../../../agent/src/compaction/prompts/auto-handoff-threshold-focus.md" with { type: "text" };
import source1 from "../../../agent/src/compaction/prompts/branch-summary-context.md" with { type: "text" };
import source2 from "../../../agent/src/compaction/prompts/branch-summary-preamble.md" with { type: "text" };
import source3 from "../../../agent/src/compaction/prompts/branch-summary.md" with { type: "text" };
import source4 from "../../../agent/src/compaction/prompts/compaction-short-summary.md" with { type: "text" };
import source5 from "../../../agent/src/compaction/prompts/compaction-summary-context.md" with { type: "text" };
import source6 from "../../../agent/src/compaction/prompts/compaction-summary.md" with { type: "text" };
import source7 from "../../../agent/src/compaction/prompts/compaction-turn-prefix.md" with { type: "text" };
import source8 from "../../../agent/src/compaction/prompts/compaction-update-summary.md" with { type: "text" };
import source9 from "../../../agent/src/compaction/prompts/context-window-truncated-output.md" with { type: "text" };
import source10 from "../../../agent/src/compaction/prompts/file-operations.md" with { type: "text" };
import source11 from "../../../agent/src/compaction/prompts/handoff-document.md" with { type: "text" };
import source12 from "../../../agent/src/compaction/prompts/snapcompact-archive-context.md" with { type: "text" };
import source13 from "../../../agent/src/compaction/prompts/summarization-system.md" with { type: "text" };
import source14 from "../autoresearch/command-resume.md" with { type: "text" };
import source15 from "../autoresearch/prompt-setup.md" with { type: "text" };
import source16 from "../autoresearch/prompt.md" with { type: "text" };
import source17 from "../autoresearch/resume-message.md" with { type: "text" };
import source18 from "../cleanse/prompts/assignment.md" with { type: "text" };
import source19 from "../cleanse/prompts/discovery.md" with { type: "text" };
import source20 from "../commit/agentic/prompts/analyze-file.md" with { type: "text" };
import source21 from "../commit/agentic/prompts/session-user.md" with { type: "text" };
import source22 from "../commit/agentic/prompts/split-confirm.md" with { type: "text" };
import source23 from "../commit/agentic/prompts/system.md" with { type: "text" };
import source24 from "../commit/prompts/analysis-system.md" with { type: "text" };
import source25 from "../commit/prompts/analysis-user.md" with { type: "text" };
import source26 from "../commit/prompts/changelog-system.md" with { type: "text" };
import source27 from "../commit/prompts/changelog-user.md" with { type: "text" };
import source28 from "../commit/prompts/file-observer-system.md" with { type: "text" };
import source29 from "../commit/prompts/file-observer-user.md" with { type: "text" };
import source30 from "../commit/prompts/reduce-system.md" with { type: "text" };
import source31 from "../commit/prompts/reduce-user.md" with { type: "text" };
import source32 from "../commit/prompts/summary-retry.md" with { type: "text" };
import source33 from "../commit/prompts/summary-system.md" with { type: "text" };
import source34 from "../commit/prompts/summary-user.md" with { type: "text" };
import source35 from "../commit/prompts/types-description.md" with { type: "text" };
import source36 from "../compress/prompts/request.md" with { type: "text" };
import source37 from "../compress/prompts/review.md" with { type: "text" };
import source38 from "../compress/prompts/system.md" with { type: "text" };
import source39 from "../discovery/builtin-rules/go-add-cleanup.md" with { type: "text" };
import source40 from "../discovery/builtin-rules/go-bench-loop.md" with { type: "text" };
import source41 from "../discovery/builtin-rules/go-exp-promoted.md" with { type: "text" };
import source42 from "../discovery/builtin-rules/go-ioutil.md" with { type: "text" };
import source43 from "../discovery/builtin-rules/go-join-hostport.md" with { type: "text" };
import source44 from "../discovery/builtin-rules/go-new-expr.md" with { type: "text" };
import source45 from "../discovery/builtin-rules/go-rand-v2.md" with { type: "text" };
import source46 from "../discovery/builtin-rules/go-range-int.md" with { type: "text" };
import source47 from "../discovery/builtin-rules/rs-box-leak.md" with { type: "text" };
import source48 from "../discovery/builtin-rules/rs-future-prelude.md" with { type: "text" };
import source49 from "../discovery/builtin-rules/rs-lazylock.md" with { type: "text" };
import source50 from "../discovery/builtin-rules/rs-match-ergonomics.md" with { type: "text" };
import source51 from "../discovery/builtin-rules/rs-parking-lot.md" with { type: "text" };
import source52 from "../discovery/builtin-rules/rs-result-type.md" with { type: "text" };
import source53 from "../discovery/builtin-rules/ts-bare-catch.md" with { type: "text" };
import source54 from "../discovery/builtin-rules/ts-import-type.md" with { type: "text" };
import source55 from "../discovery/builtin-rules/ts-no-any.md" with { type: "text" };
import source56 from "../discovery/builtin-rules/ts-no-deprecated-leftovers.md" with { type: "text" };
import source57 from "../discovery/builtin-rules/ts-no-dynamic-import.md" with { type: "text" };
import source58 from "../discovery/builtin-rules/ts-no-inline-cast-access.md" with { type: "text" };
import source59 from "../discovery/builtin-rules/ts-no-local-is-record.md" with { type: "text" };
import source60 from "../discovery/builtin-rules/ts-no-return-type.md" with { type: "text" };
import source61 from "../discovery/builtin-rules/ts-no-test-timers.md" with { type: "text" };
import source62 from "../discovery/builtin-rules/ts-no-tiny-functions.md" with { type: "text" };
import source63 from "../discovery/builtin-rules/ts-promise-with-resolvers.md" with { type: "text" };
import source64 from "../discovery/builtin-rules/ts-redundant-clear-guard.md" with { type: "text" };
import source65 from "../discovery/builtin-rules/ts-set-map.md" with { type: "text" };
import source66 from "../live/prompts/agent-final-message.md" with { type: "text" };
import source67 from "../live/prompts/live-instructions.md" with { type: "text" };
import source68 from "../prompts/advisor/active-repo-watchdog.md" with { type: "text" };
import source69 from "../prompts/advisor/advise-tool.md" with { type: "text" };
import source70 from "../prompts/advisor/context-files.md" with { type: "text" };
import source71 from "../prompts/advisor/system.md" with { type: "text" };
import source72 from "../prompts/agents/designer.md" with { type: "text" };
import source73 from "../prompts/agents/frontmatter.md" with { type: "text" };
import source74 from "../prompts/agents/init.md" with { type: "text" };
import source75 from "../prompts/agents/librarian.md" with { type: "text" };
import source76 from "../prompts/agents/reviewer.md" with { type: "text" };
import source77 from "../prompts/agents/scout.md" with { type: "text" };
import source78 from "../prompts/agents/security-reviewer.md" with { type: "text" };
import source79 from "../prompts/agents/task.md" with { type: "text" };
import source80 from "../prompts/bench.md" with { type: "text" };
import source81 from "../prompts/bench/cache-prefix-chunk.md" with { type: "text" };
import source82 from "../prompts/bench/cache-prefix.md" with { type: "text" };
import source83 from "../prompts/bench/cache-suffix.md" with { type: "text" };
import source84 from "../prompts/ci-green-request.md" with { type: "text" };
import source85 from "../prompts/dry-balance-bench.md" with { type: "text" };
import source86 from "../prompts/goals/goal-budget-limit.md" with { type: "text" };
import source87 from "../prompts/goals/goal-continuation.md" with { type: "text" };
import source88 from "../prompts/goals/goal-mode-active.md" with { type: "text" };
import source89 from "../prompts/goals/goal-mode-context.md" with { type: "text" };
import source90 from "../prompts/goals/goal-objective-updated.md" with { type: "text" };
import source91 from "../prompts/goals/goal-todo-context.md" with { type: "text" };
import source92 from "../prompts/goals/guided-goal-interview.md" with { type: "text" };
import source93 from "../prompts/memories/consolidation_system.md" with { type: "text" };
import source94 from "../prompts/memories/consolidation.md" with { type: "text" };
import source95 from "../prompts/memories/read-path.md" with { type: "text" };
import source96 from "../prompts/memories/stage_one_input.md" with { type: "text" };
import source97 from "../prompts/memories/stage_one_system.md" with { type: "text" };
import source98 from "../prompts/providers/internal-context.md" with { type: "text" };
import source99 from "../prompts/review-custom-request.md" with { type: "text" };
import source100 from "../prompts/review-headless-request.md" with { type: "text" };
import source101 from "../prompts/review-request.md" with { type: "text" };
import source102 from "../prompts/security/scan-coordinator.md" with { type: "text" };
import source103 from "../prompts/security/scan-request.md" with { type: "text" };
import source104 from "../prompts/security/validate-request.md" with { type: "text" };
import source105 from "../prompts/session/launch-completion.md" with { type: "text" };
import source106 from "../prompts/skills/autoload.md" with { type: "text" };
import source107 from "../prompts/skills/smarty-mergify-policy.md" with { type: "text" };
import source108 from "../prompts/skills/user-invocation.md" with { type: "text" };
import source109 from "../prompts/steering/parent-irc.md" with { type: "text" };
import source110 from "../prompts/steering/user-interjection.md" with { type: "text" };
import source111 from "../prompts/system/active-repo-context.md" with { type: "text" };
import source112 from "../prompts/system/agent-creation-architect.md" with { type: "text" };
import source113 from "../prompts/system/agent-creation-user.md" with { type: "text" };
import source114 from "../prompts/system/auto-continue.md" with { type: "text" };
import source115 from "../prompts/system/auto-thinking-difficulty-local.md" with { type: "text" };
import source116 from "../prompts/system/auto-thinking-difficulty.md" with { type: "text" };
import source117 from "../prompts/system/autolearn-guidance-learn.md" with { type: "text" };
import source118 from "../prompts/system/autolearn-guidance.md" with { type: "text" };
import source119 from "../prompts/system/autolearn-nudge-autocontinue.md" with { type: "text" };
import source120 from "../prompts/system/background-tan-dispatch.md" with { type: "text" };
import source121 from "../prompts/system/btw-user.md" with { type: "text" };
import source122 from "../prompts/system/checkpoint-active-notice.md" with { type: "text" };
import source123 from "../prompts/system/commit-message-system.md" with { type: "text" };
import source124 from "../prompts/system/computer-safety.md" with { type: "text" };
import source125 from "../prompts/system/custom-system-prompt.md" with { type: "text" };
import source126 from "../prompts/system/date-cwd-reminder.md" with { type: "text" };
import source127 from "../prompts/system/eager-task.md" with { type: "text" };
import source128 from "../prompts/system/eager-todo.md" with { type: "text" };
import source129 from "../prompts/system/empty-stop-retry.md" with { type: "text" };
import source130 from "../prompts/system/gemini-tool-call-reminder.md" with { type: "text" };
import source131 from "../prompts/system/interrupted-thinking.md" with { type: "text" };
import source132 from "../prompts/system/irc-autoreply.md" with { type: "text" };
import source133 from "../prompts/system/irc-incoming.md" with { type: "text" };
import source134 from "../prompts/system/manual-continue.md" with { type: "text" };
import source135 from "../prompts/system/mcp-xdev-guidance.md" with { type: "text" };
import source136 from "../prompts/system/memory-consolidation-system.md" with { type: "text" };
import source137 from "../prompts/system/memory-extraction-system.md" with { type: "text" };
import source138 from "../prompts/system/mid-run-todo-nudge.md" with { type: "text" };
import source139 from "../prompts/system/omfg-user.md" with { type: "text" };
import source140 from "../prompts/system/orchestrate-notice.md" with { type: "text" };
import source141 from "../prompts/system/personalities/default.md" with { type: "text" };
import source142 from "../prompts/system/personalities/friendly.md" with { type: "text" };
import source143 from "../prompts/system/personalities/pragmatic.md" with { type: "text" };
import source144 from "../prompts/system/plan-mode-active.md" with { type: "text" };
import source145 from "../prompts/system/plan-mode-approved.md" with { type: "text" };
import source146 from "../prompts/system/plan-mode-compact-instructions.md" with { type: "text" };
import source147 from "../prompts/system/plan-mode-reference.md" with { type: "text" };
import source148 from "../prompts/system/plan-mode-subagent.md" with { type: "text" };
import source149 from "../prompts/system/plan-mode-tool-decision-reminder.md" with { type: "text" };
import source150 from "../prompts/system/plan-yolo-handoff.md" with { type: "text" };
import source151 from "../prompts/system/prewalk-checklist.md" with { type: "text" };
import source152 from "../prompts/system/prewalk-continue.md" with { type: "text" };
import source153 from "../prompts/system/prewalk-plan.md" with { type: "text" };
import source154 from "../prompts/system/project-prompt.md" with { type: "text" };
import source155 from "../prompts/system/recap-user.md" with { type: "text" };
import source156 from "../prompts/system/resolve-device-reminder.md" with { type: "text" };
import source157 from "../prompts/system/rewind-report.md" with { type: "text" };
import source158 from "../prompts/system/side-channel-no-tools.md" with { type: "text" };
import source159 from "../prompts/system/snapcompact-context-frames-note.md" with { type: "text" };
import source160 from "../prompts/system/snapcompact-context-stub.md" with { type: "text" };
import source161 from "../prompts/system/snapcompact-system-frames-note.md" with { type: "text" };
import source162 from "../prompts/system/snapcompact-system-stub.md" with { type: "text" };
import source163 from "../prompts/system/snapcompact-toolresult-note.md" with { type: "text" };
import source164 from "../prompts/system/speech-rewrite.md" with { type: "text" };
import source165 from "../prompts/system/subagent-async-pending.md" with { type: "text" };
import source166 from "../prompts/system/subagent-system-prompt.md" with { type: "text" };
import source167 from "../prompts/system/subagent-user-prompt.md" with { type: "text" };
import source168 from "../prompts/system/system-prompt.md" with { type: "text" };
import source169 from "../prompts/system/tan-context-switch.md" with { type: "text" };
import source170 from "../prompts/system/task-label.md" with { type: "text" };
import source171 from "../prompts/system/thinking-loop-redirect.md" with { type: "text" };
import source172 from "../prompts/system/title-marker-instruction.md" with { type: "text" };
import source173 from "../prompts/system/title-system.md" with { type: "text" };
import source174 from "../prompts/system/tool-call-loop-redirect.md" with { type: "text" };
import source175 from "../prompts/system/ttsr-interrupt.md" with { type: "text" };
import source176 from "../prompts/system/ttsr-tool-reminder.md" with { type: "text" };
import source177 from "../prompts/system/ultrathink-notice.md" with { type: "text" };
import source178 from "../prompts/system/unexpected-stop-classifier.md" with { type: "text" };
import source179 from "../prompts/system/unexpected-stop-retry.md" with { type: "text" };
import source180 from "../prompts/system/vibe-mode-active.md" with { type: "text" };
import source181 from "../prompts/system/web-search.md" with { type: "text" };
import source182 from "../prompts/system/workflow-notice.md" with { type: "text" };
import source183 from "../prompts/system/xdev-mount-notice.md" with { type: "text" };
import source184 from "../prompts/todos/current.md" with { type: "text" };
import source185 from "../prompts/tools/apply-patch.md" with { type: "text" };
import source186 from "../prompts/tools/approve.md" with { type: "text" };
import source187 from "../prompts/tools/ask.md" with { type: "text" };
import source188 from "../prompts/tools/ast-edit.md" with { type: "text" };
import source189 from "../prompts/tools/ast-grep.md" with { type: "text" };
import source190 from "../prompts/tools/async-result.md" with { type: "text" };
import source191 from "../prompts/tools/bash.md" with { type: "text" };
import source192 from "../prompts/tools/browser.md" with { type: "text" };
import source193 from "../prompts/tools/checkpoint.md" with { type: "text" };
import source194 from "../prompts/tools/computer.md" with { type: "text" };
import source195 from "../prompts/tools/debug.md" with { type: "text" };
import source196 from "../prompts/tools/eval.md" with { type: "text" };
import source197 from "../prompts/tools/github.md" with { type: "text" };
import source198 from "../prompts/tools/glob.md" with { type: "text" };
import source199 from "../prompts/tools/goal.md" with { type: "text" };
import source200 from "../prompts/tools/grep.md" with { type: "text" };
import source201 from "../prompts/tools/hub.md" with { type: "text" };
import source202 from "../prompts/tools/image-attachment-describe-system.md" with { type: "text" };
import source203 from "../prompts/tools/image-attachment-describe.md" with { type: "text" };
import source204 from "../prompts/tools/image-gen.md" with { type: "text" };
import source205 from "../prompts/tools/inspect-image-system.md" with { type: "text" };
import source206 from "../prompts/tools/inspect-image.md" with { type: "text" };
import source207 from "../prompts/tools/learn.md" with { type: "text" };
import source208 from "../prompts/tools/lsp-late-diagnostic.md" with { type: "text" };
import source209 from "../prompts/tools/lsp.md" with { type: "text" };
import source210 from "../prompts/tools/manage-skill.md" with { type: "text" };
import source211 from "../prompts/tools/memory-edit.md" with { type: "text" };
import source212 from "../prompts/tools/patch.md" with { type: "text" };
import source213 from "../prompts/tools/read.md" with { type: "text" };
import source214 from "../prompts/tools/recall.md" with { type: "text" };
import source215 from "../prompts/tools/reflect.md" with { type: "text" };
import source216 from "../prompts/tools/replace.md" with { type: "text" };
import source217 from "../prompts/tools/retain.md" with { type: "text" };
import source218 from "../prompts/tools/rewind.md" with { type: "text" };
import source219 from "../prompts/tools/rewrite.md" with { type: "text" };
import source220 from "../prompts/tools/security-publish.md" with { type: "text" };
import source221 from "../prompts/tools/security-scan.md" with { type: "text" };
import source222 from "../prompts/tools/task-async-contract.md" with { type: "text" };
import source223 from "../prompts/tools/task-summary.md" with { type: "text" };
import source224 from "../prompts/tools/task.md" with { type: "text" };
import source225 from "../prompts/tools/todo.md" with { type: "text" };
import source226 from "../prompts/tools/vibe-kill.md" with { type: "text" };
import source227 from "../prompts/tools/vibe-list.md" with { type: "text" };
import source228 from "../prompts/tools/vibe-send.md" with { type: "text" };
import source229 from "../prompts/tools/vibe-spawn.md" with { type: "text" };
import source230 from "../prompts/tools/vibe-turn-result.md" with { type: "text" };
import source231 from "../prompts/tools/vibe-wait.md" with { type: "text" };
import source232 from "../prompts/tools/web-search.md" with { type: "text" };
import source233 from "../prompts/tools/write.md" with { type: "text" };

export const PROMPT_SOURCES: Readonly<Record<string, string>> = Object.freeze({
	"_agent/compaction/prompts/auto-handoff-threshold-focus.md": source0,
	"_agent/compaction/prompts/branch-summary-context.md": source1,
	"_agent/compaction/prompts/branch-summary-preamble.md": source2,
	"_agent/compaction/prompts/branch-summary.md": source3,
	"_agent/compaction/prompts/compaction-short-summary.md": source4,
	"_agent/compaction/prompts/compaction-summary-context.md": source5,
	"_agent/compaction/prompts/compaction-summary.md": source6,
	"_agent/compaction/prompts/compaction-turn-prefix.md": source7,
	"_agent/compaction/prompts/compaction-update-summary.md": source8,
	"_agent/compaction/prompts/context-window-truncated-output.md": source9,
	"_agent/compaction/prompts/file-operations.md": source10,
	"_agent/compaction/prompts/handoff-document.md": source11,
	"_agent/compaction/prompts/snapcompact-archive-context.md": source12,
	"_agent/compaction/prompts/summarization-system.md": source13,
	"autoresearch/command-resume.md": source14,
	"autoresearch/prompt-setup.md": source15,
	"autoresearch/prompt.md": source16,
	"autoresearch/resume-message.md": source17,
	"cleanse/prompts/assignment.md": source18,
	"cleanse/prompts/discovery.md": source19,
	"commit/agentic/prompts/analyze-file.md": source20,
	"commit/agentic/prompts/session-user.md": source21,
	"commit/agentic/prompts/split-confirm.md": source22,
	"commit/agentic/prompts/system.md": source23,
	"commit/prompts/analysis-system.md": source24,
	"commit/prompts/analysis-user.md": source25,
	"commit/prompts/changelog-system.md": source26,
	"commit/prompts/changelog-user.md": source27,
	"commit/prompts/file-observer-system.md": source28,
	"commit/prompts/file-observer-user.md": source29,
	"commit/prompts/reduce-system.md": source30,
	"commit/prompts/reduce-user.md": source31,
	"commit/prompts/summary-retry.md": source32,
	"commit/prompts/summary-system.md": source33,
	"commit/prompts/summary-user.md": source34,
	"commit/prompts/types-description.md": source35,
	"compress/prompts/request.md": source36,
	"compress/prompts/review.md": source37,
	"compress/prompts/system.md": source38,
	"discovery/builtin-rules/go-add-cleanup.md": source39,
	"discovery/builtin-rules/go-bench-loop.md": source40,
	"discovery/builtin-rules/go-exp-promoted.md": source41,
	"discovery/builtin-rules/go-ioutil.md": source42,
	"discovery/builtin-rules/go-join-hostport.md": source43,
	"discovery/builtin-rules/go-new-expr.md": source44,
	"discovery/builtin-rules/go-rand-v2.md": source45,
	"discovery/builtin-rules/go-range-int.md": source46,
	"discovery/builtin-rules/rs-box-leak.md": source47,
	"discovery/builtin-rules/rs-future-prelude.md": source48,
	"discovery/builtin-rules/rs-lazylock.md": source49,
	"discovery/builtin-rules/rs-match-ergonomics.md": source50,
	"discovery/builtin-rules/rs-parking-lot.md": source51,
	"discovery/builtin-rules/rs-result-type.md": source52,
	"discovery/builtin-rules/ts-bare-catch.md": source53,
	"discovery/builtin-rules/ts-import-type.md": source54,
	"discovery/builtin-rules/ts-no-any.md": source55,
	"discovery/builtin-rules/ts-no-deprecated-leftovers.md": source56,
	"discovery/builtin-rules/ts-no-dynamic-import.md": source57,
	"discovery/builtin-rules/ts-no-inline-cast-access.md": source58,
	"discovery/builtin-rules/ts-no-local-is-record.md": source59,
	"discovery/builtin-rules/ts-no-return-type.md": source60,
	"discovery/builtin-rules/ts-no-test-timers.md": source61,
	"discovery/builtin-rules/ts-no-tiny-functions.md": source62,
	"discovery/builtin-rules/ts-promise-with-resolvers.md": source63,
	"discovery/builtin-rules/ts-redundant-clear-guard.md": source64,
	"discovery/builtin-rules/ts-set-map.md": source65,
	"live/prompts/agent-final-message.md": source66,
	"live/prompts/live-instructions.md": source67,
	"prompts/advisor/active-repo-watchdog.md": source68,
	"prompts/advisor/advise-tool.md": source69,
	"prompts/advisor/context-files.md": source70,
	"prompts/advisor/system.md": source71,
	"prompts/agents/designer.md": source72,
	"prompts/agents/frontmatter.md": source73,
	"prompts/agents/init.md": source74,
	"prompts/agents/librarian.md": source75,
	"prompts/agents/reviewer.md": source76,
	"prompts/agents/scout.md": source77,
	"prompts/agents/security-reviewer.md": source78,
	"prompts/agents/task.md": source79,
	"prompts/bench.md": source80,
	"prompts/bench/cache-prefix-chunk.md": source81,
	"prompts/bench/cache-prefix.md": source82,
	"prompts/bench/cache-suffix.md": source83,
	"prompts/ci-green-request.md": source84,
	"prompts/dry-balance-bench.md": source85,
	"prompts/goals/goal-budget-limit.md": source86,
	"prompts/goals/goal-continuation.md": source87,
	"prompts/goals/goal-mode-active.md": source88,
	"prompts/goals/goal-mode-context.md": source89,
	"prompts/goals/goal-objective-updated.md": source90,
	"prompts/goals/goal-todo-context.md": source91,
	"prompts/goals/guided-goal-interview.md": source92,
	"prompts/memories/consolidation_system.md": source93,
	"prompts/memories/consolidation.md": source94,
	"prompts/memories/read-path.md": source95,
	"prompts/memories/stage_one_input.md": source96,
	"prompts/memories/stage_one_system.md": source97,
	"prompts/providers/internal-context.md": source98,
	"prompts/review-custom-request.md": source99,
	"prompts/review-headless-request.md": source100,
	"prompts/review-request.md": source101,
	"prompts/security/scan-coordinator.md": source102,
	"prompts/security/scan-request.md": source103,
	"prompts/security/validate-request.md": source104,
	"prompts/session/launch-completion.md": source105,
	"prompts/skills/autoload.md": source106,
	"prompts/skills/smarty-mergify-policy.md": source107,
	"prompts/skills/user-invocation.md": source108,
	"prompts/steering/parent-irc.md": source109,
	"prompts/steering/user-interjection.md": source110,
	"prompts/system/active-repo-context.md": source111,
	"prompts/system/agent-creation-architect.md": source112,
	"prompts/system/agent-creation-user.md": source113,
	"prompts/system/auto-continue.md": source114,
	"prompts/system/auto-thinking-difficulty-local.md": source115,
	"prompts/system/auto-thinking-difficulty.md": source116,
	"prompts/system/autolearn-guidance-learn.md": source117,
	"prompts/system/autolearn-guidance.md": source118,
	"prompts/system/autolearn-nudge-autocontinue.md": source119,
	"prompts/system/background-tan-dispatch.md": source120,
	"prompts/system/btw-user.md": source121,
	"prompts/system/checkpoint-active-notice.md": source122,
	"prompts/system/commit-message-system.md": source123,
	"prompts/system/computer-safety.md": source124,
	"prompts/system/custom-system-prompt.md": source125,
	"prompts/system/date-cwd-reminder.md": source126,
	"prompts/system/eager-task.md": source127,
	"prompts/system/eager-todo.md": source128,
	"prompts/system/empty-stop-retry.md": source129,
	"prompts/system/gemini-tool-call-reminder.md": source130,
	"prompts/system/interrupted-thinking.md": source131,
	"prompts/system/irc-autoreply.md": source132,
	"prompts/system/irc-incoming.md": source133,
	"prompts/system/manual-continue.md": source134,
	"prompts/system/mcp-xdev-guidance.md": source135,
	"prompts/system/memory-consolidation-system.md": source136,
	"prompts/system/memory-extraction-system.md": source137,
	"prompts/system/mid-run-todo-nudge.md": source138,
	"prompts/system/omfg-user.md": source139,
	"prompts/system/orchestrate-notice.md": source140,
	"prompts/system/personalities/default.md": source141,
	"prompts/system/personalities/friendly.md": source142,
	"prompts/system/personalities/pragmatic.md": source143,
	"prompts/system/plan-mode-active.md": source144,
	"prompts/system/plan-mode-approved.md": source145,
	"prompts/system/plan-mode-compact-instructions.md": source146,
	"prompts/system/plan-mode-reference.md": source147,
	"prompts/system/plan-mode-subagent.md": source148,
	"prompts/system/plan-mode-tool-decision-reminder.md": source149,
	"prompts/system/plan-yolo-handoff.md": source150,
	"prompts/system/prewalk-checklist.md": source151,
	"prompts/system/prewalk-continue.md": source152,
	"prompts/system/prewalk-plan.md": source153,
	"prompts/system/project-prompt.md": source154,
	"prompts/system/recap-user.md": source155,
	"prompts/system/resolve-device-reminder.md": source156,
	"prompts/system/rewind-report.md": source157,
	"prompts/system/side-channel-no-tools.md": source158,
	"prompts/system/snapcompact-context-frames-note.md": source159,
	"prompts/system/snapcompact-context-stub.md": source160,
	"prompts/system/snapcompact-system-frames-note.md": source161,
	"prompts/system/snapcompact-system-stub.md": source162,
	"prompts/system/snapcompact-toolresult-note.md": source163,
	"prompts/system/speech-rewrite.md": source164,
	"prompts/system/subagent-async-pending.md": source165,
	"prompts/system/subagent-system-prompt.md": source166,
	"prompts/system/subagent-user-prompt.md": source167,
	"prompts/system/system-prompt.md": source168,
	"prompts/system/tan-context-switch.md": source169,
	"prompts/system/task-label.md": source170,
	"prompts/system/thinking-loop-redirect.md": source171,
	"prompts/system/title-marker-instruction.md": source172,
	"prompts/system/title-system.md": source173,
	"prompts/system/tool-call-loop-redirect.md": source174,
	"prompts/system/ttsr-interrupt.md": source175,
	"prompts/system/ttsr-tool-reminder.md": source176,
	"prompts/system/ultrathink-notice.md": source177,
	"prompts/system/unexpected-stop-classifier.md": source178,
	"prompts/system/unexpected-stop-retry.md": source179,
	"prompts/system/vibe-mode-active.md": source180,
	"prompts/system/web-search.md": source181,
	"prompts/system/workflow-notice.md": source182,
	"prompts/system/xdev-mount-notice.md": source183,
	"prompts/todos/current.md": source184,
	"prompts/tools/apply-patch.md": source185,
	"prompts/tools/approve.md": source186,
	"prompts/tools/ask.md": source187,
	"prompts/tools/ast-edit.md": source188,
	"prompts/tools/ast-grep.md": source189,
	"prompts/tools/async-result.md": source190,
	"prompts/tools/bash.md": source191,
	"prompts/tools/browser.md": source192,
	"prompts/tools/checkpoint.md": source193,
	"prompts/tools/computer.md": source194,
	"prompts/tools/debug.md": source195,
	"prompts/tools/eval.md": source196,
	"prompts/tools/github.md": source197,
	"prompts/tools/glob.md": source198,
	"prompts/tools/goal.md": source199,
	"prompts/tools/grep.md": source200,
	"prompts/tools/hub.md": source201,
	"prompts/tools/image-attachment-describe-system.md": source202,
	"prompts/tools/image-attachment-describe.md": source203,
	"prompts/tools/image-gen.md": source204,
	"prompts/tools/inspect-image-system.md": source205,
	"prompts/tools/inspect-image.md": source206,
	"prompts/tools/learn.md": source207,
	"prompts/tools/lsp-late-diagnostic.md": source208,
	"prompts/tools/lsp.md": source209,
	"prompts/tools/manage-skill.md": source210,
	"prompts/tools/memory-edit.md": source211,
	"prompts/tools/patch.md": source212,
	"prompts/tools/read.md": source213,
	"prompts/tools/recall.md": source214,
	"prompts/tools/reflect.md": source215,
	"prompts/tools/replace.md": source216,
	"prompts/tools/retain.md": source217,
	"prompts/tools/rewind.md": source218,
	"prompts/tools/rewrite.md": source219,
	"prompts/tools/security-publish.md": source220,
	"prompts/tools/security-scan.md": source221,
	"prompts/tools/task-async-contract.md": source222,
	"prompts/tools/task-summary.md": source223,
	"prompts/tools/task.md": source224,
	"prompts/tools/todo.md": source225,
	"prompts/tools/vibe-kill.md": source226,
	"prompts/tools/vibe-list.md": source227,
	"prompts/tools/vibe-send.md": source228,
	"prompts/tools/vibe-spawn.md": source229,
	"prompts/tools/vibe-turn-result.md": source230,
	"prompts/tools/vibe-wait.md": source231,
	"prompts/tools/web-search.md": source232,
	"prompts/tools/write.md": source233,
});
